name: Label PR

on:
  pull_request_target: {}

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: srvaroa/labeler@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
