name: Perform PR actions

on:
  pull_request_target: {}

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: srvaroa/labeler@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  enable-auto-merge:
    needs: label-pr
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    permissions:
      contents: write
    steps:
    - run: gh pr merge --merge --auto "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
